### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by whitequark** [ppd1990/solvespace-snap#2]
There's a Flatpak package upstream already. Any interest in upstreaming the snap? It seems very similar, although I haven't looked at it in depth.

**Comment by ppd** [comment]
Absolutely. How shall we proceed? I suppose fixing #1, incorporating this repo into https://github.com/solvespace/solvespace and then transferring the solvespace snap registration to a "SolveSpace" publisher account is the way to go.

**Comment by whitequark** [comment]
Sounds reasonable.

**Comment by ppd** [comment]
Integration of this repo into upstream proposed here:
https://github.com/solvespace/solvespace/pull/436

**Comment by ppd** [comment]
Merged upstream
